### ISSUE TITLE
请问下绑定多网盘是怎么配置json。

### ISSUE THREAD

**Issue by 955s** [MoeClub/OneList#10]
![QQ图片20191226202238](https://user-images.githubusercontent.com/14900130/71475922-7af10580-281d-11ea-9c25-5c139ec84177.png)
![QQ图片20191226202304](https://user-images.githubusercontent.com/14900130/71475923-7af10580-281d-11ea-8728-104dea0f5968.png)

**Comment by 0oVicero0** [comment]
多网盘是 Go 版的特征
多运行几次 -a 授权就能看懂了配置文件格式了。
