### ISSUE TITLE
Windows版本64位不兼容啊

### ISSUE THREAD

**Issue by hl668** [MoeClub/OneList#14]

**Comment by hl668** [comment]
我下载你的那个64位Windows的，然后运行 OneDriveUploader.exe -a "url"
  显示不兼容    显示的内容是:该版本的 C:\Users\Administrator\Downloads\Programs\OneDriveUploader.exe 与你运行的 Windows 版本不兼容。请查看计算机的系 统信息，然后联系软件发布者。我电脑就是64位的

**Comment by yh56789** [comment]
我的也是，64位版本不兼容

**Comment by MoeClub** [comment]
多半是下载错了。
每个页面，我增加了下载提示。
按提示下载吧
