### ISSUE TITLE
access roken 1小时有效期

### ISSUE THREAD

**Issue by yumin9822** [MoeClub/OneList#17]
The access token has expired. It's valid from '1/9/2020 5:03:31 AM' and to '1/9/2020 6:03:31 AM'.

由于盘内文件比较多，每次cache都要花费接近一小时，所有经常出现上述错误。请问有办法增加access token的有效期吗，比如24或72小时之类的。

**Comment by MoeClub** [comment]
这是微软规定的，无法修改。
---
你可以将一个盘分成多个 `SubPath`，用来提速缓存。
