### ISSUE TITLE
[美化]有没有人知道怎么让onelist调用css文件？

### ISSUE THREAD

**Issue by NOAME18** [MoeClub/OneList#35]
我改了个网页模板但是做完才发现onelist完全不管css文件，只调用了index.html，结果变成这个样..
![Snipaste_2020-02-18_16-31-43](https://user-images.githubusercontent.com/53110680/74717923-36597780-526c-11ea-885c-3f3757cebf5f.png)
![Snipaste_2020-02-18_16-29-26](https://user-images.githubusercontent.com/53110680/74717932-39546800-526c-11ea-9356-5027ab7f761e.png)

**Comment by ruanun** [comment]
内嵌 CSS。试试

**Comment by NOAME18** [comment]
试了几遍我懂了，onelist调用资源的目录路径和index.html的路径重合一起了，里面的引用不能是相对路径
1.可以内嵌解决
2.应用外部链接
如果是相对路径的话，那么你网页的目录css等等文件可以调到onedrive那里存储，调用的路径必须对才行，当然这样做的话还不如直接套一个的onedrive外链，省得onelist调用api了
