### ISSUE TITLE
显示Cache: Done 但无法访问，端口开的8000，似乎并未正确监听？

### ISSUE THREAD

**Issue by yaonyan** [MoeClub/OneList#51]
- 执行的是
```
/opt/OneList/OneList -bind 0.0.0.0 -port 8000
```
- 缓存完后，返回了 Cache: Done

- 端口状态如下 
![image](https://user-images.githubusercontent.com/63141491/81390549-4176c200-914e-11ea-8c10-3ef2ac24601c.png)
- 但前端访问超时（已检查subpath）

> 诚心求助，感谢

**Comment by yaonyan** [comment]
。

**Comment by yaonyan** [comment]
已成功

**Comment by desgrtgsth** [comment]
如何解决的？
